# This list of English stop words is taken from the "Glasgow Information
# Retrieval Group". The original list can be found at
# http://ir.dcs.gla.ac.uk/resources/linguistic_utils/stop_words
ENGLISH_STOP_WORDS = frozenset([
    "a", "about", "above", "across", "after", "afterwards", "again", "against",
    "all", "almost", "alone", "along", "already", "also", "although", 
    "am", "among", "amongst", "amoungst", "amount", "an", "and", "another",
    "anyhow", "anyone", "anything", "anyway", "anywhere", "are",
    "around", "as", "at", "back", "be", "because", 
    "been", "before", "beforehand", "behind", "being",
    "below", "beside", "besides", "between", "beyond", "bill", "both",
    "bottom", "but", "by", "call", "co", "con",
    "cry", "de", "describe", "detail", 
    "due", "during", "each", "eg", "eight", "either", "eleven", "else",
    "elsewhere", "empty", "etc", "ever", "every", "everyone",
    "everything", "everywhere", "few", "fifteen", "fify", "fill",
    "fire", "first", "five", "for", "former", "formerly", "forty",
    "four", "from", "front", "full", "further", "go",
    "he", "hence", "her", "here", "hereafter",
    "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his",
    "how", "however", "hundred", "i", "ie", "if", "in", "inc", "indeed",
    "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter",
    "latterly", "least", "ltd", "me",
    "meanwhile", "mill", "mine", "moreover", "most", "mostly",
    "my", "myself", "name", "namely", "neither",
    "nevertheless", "next", "nine", "nobody", "noone",
    "nor", "nothing", "now", "nowhere", "of", "often", "on",
    "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our",
    "ours", "ourselves", "out", "over", "own", "part", "per", "perhaps",
    "put", "rather", "re", "same", 
    "several", "she", "side",
    "since", "sincere", "six", "sixty", "some", "somehow", "someone",
    "something", "sometime", "sometimes", "somewhere", "such",
    "system", "ten", "that", "the", "their", "them",
    "themselves", "then", "thence", "there", "thereafter", "thereby",
    "therefore", "therein", "thereupon", "these", "they", "thick", "thin",
    "third", "this", "those", "though", "three", "through", "throughout",
    "thru", "thus", "to", "together", "top", "toward", "towards",
    "twelve", "twenty", "two", "under", "until", "up", "upon", "us",
    "via", "was", "we", "were", "what", "whatever", "when",
    "whence", "whenever", "where", "whereafter", "whereas", "whereby",
    "wherein", "whereupon", "wherever", "whether", "which", "while", "whither",
    "who", "whoever", "whole", "whom", "whose", "why", 
    "within", "you", "your", "yours", "yourself",
    "yourselves", "jira", "trello"])
